# Use official Node image
FROM node:18

# Set working directory
WORKDIR /app

# Accept build-time variables
ARG NODE_ENV

# Set them as environment variables inside container
ENV NODE_ENV=$NODE_ENV

# Copy package files first (for caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of code
COPY . .

# Expose port
# Default port (can be overridden)
ENV PORT=3002
EXPOSE $PORT

# Start app
CMD ["npm", "start"]