name: Deploy App to DigitalOcean

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Install dependencies circlewash
      #   working-directory: ./circlewash
      #   run: npm install

      # - name: Install dependencies circlewashstaff
      #   working-directory: ./circlewashstaff
      #   run: npm install
      
      # - name: Install dependencies new-circlewash-frontend
      #   working-directory: ./new-circlewash-frontend
      #   run: npm install

      # Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      # Add droplet to known hosts
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      # Deploy via SSH
      - name: Deploy to Droplet
        run: |
          ssh ${{ secrets.DO_USERNAME }}@${{ secrets.DO_HOST }} << 'EOF'
            REPO_URL=https://github.com/${{ github.repository }}.git

            if [ ! -d ${{ secrets.DO_APP_DIR }} ]; then
              echo "Cloning repository..."
              git clone $REPO_URL ${{ secrets.DO_APP_DIR }}
            else
              echo "Repository exists, pulling latest..."
              cd ${{ secrets.DO_APP_DIR }}
              git pull origin main
            fi

            cd ${{ secrets.DO_APP_DIR }}

            echo "create .env file"
            echo "NODE_ENV=development" >> .env
            echo "CIRCLEWASH_LEGACY_PUBLIC_FACING_PORT=${{ vars.CIRCLEWASH_LEGACY_PUBLIC_FACING_PORT }}" >> .env
            echo "CIRCLEWASH_NEW_PUBLIC_FACING_PORT=${{ vars.CIRCLEWASH_NEW_PUBLIC_FACING_PORT }}" >> .env
            echo "CIRCLEWASH_ADMIN_PORTAL_PORT=${{ vars.CIRCLEWASH_ADMIN_PORTAL_PORT }}" >> .env
            echo "CHAT_SERVICE_PORT=${{ vars.CHAT_SERVICE_PORT }}" >> .env
            echo "CUSTOMER_SERVICE_PORT=${{ vars.CUSTOMER_SERVICE_PORT }}" >> .env
            echo "EMPLOYEE_SERVICE_PORT=${{ vars.EMPLOYEE_SERVICE_PORT }}" >> .env
            echo "GATEWAY_PORT=${{ vars.GATEWAY_PORT }}" >> .env
            echo "MACHINE_SERVICE_PORT=${{ vars.MACHINE_SERVICE_PORT }}" >> .env
            echo "NOTIFICATION_SERVICE_PORT=${{ vars.NOTIFICATION_SERVICE_PORT }}" >> .env
            echo "SUPPORT_CASE_SERVICE_PORT=${{ vars.SUPPORT_CASE_SERVICE_PORT }}" >> .env
            echo "DB_HOST=${{ vars.DB_HOST }}" >> .env
            echo "MONGO_PORT=${{ vars.MONGO_PORT }}" >> .env
            echo "MONGO_USER=${{ secrets.MONGO_USER }}" >> .env
            echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
            echo "MONGO_DB_NAME=${{ vars.MONGO_DB_NAME }}" >> .env
            echo "MONGO_URI=${{ vars.MONGO_URI }}" >> .env
            echo "REDIS_HOST=${{ vars.REDIS_HOST }}" >> .env
            echo "REDIS_PORT=${{ vars.REDIS_PORT }}" >> .env
            echo "REDIS_ADMIN_PORT=${{ vars.REDIS_ADMIN_PORT }}" >> .env
            echo "RABBITMQ_HOST=${{ vars.RABBITMQ_HOST }}" >> .env
            echo "RABBITMQ_URL=${{vars.RABBITMQ_URL}}" >> .env
            echo "RABBITMQ_ADMIN_TOOL_URL=${{vars.RABBITMQ_ADMIN_TOOL_URL}}" >> .env
            echo "RABBITMQ_PORT=${{vars.RABBITMQ_PORT}}" >> .env
            echo "RABBITMQ_ADMIN_PORT=${{vars.RABBITMQ_ADMIN_PORT}}" >> .env
            echo "RABBITMQ_USER=${{ secrets.RABBITMQ_USER }}" >> .env
            echo "RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}" >> .env
            echo "RABBITMQ_EXCHANGE_NAME=${{ vars.RABBITMQ_EXCHANGE_NAME }}" >> .env
            echo "RABBITMQ_MACHINE_ROUTING_KEY=${{ vars.RABBITMQ_MACHINE_ROUTING_KEY }}" >> .env
            echo "RABBITMQ_EMPLOYEE_ROUTING_KEY=${{ vars.RABBITMQ_EMPLOYEE_ROUTING_KEY }}" >> .env
            echo "RABBITMQ_SUPPORT_CASE_ROUTING_KEY=${{ vars.RABBITMQ_SUPPORT_CASE_ROUTING_KEY }}" >> .env
            echo "RABBITMQ_MACHINE_QUEUE_BINDING_KEY=${{ vars.RABBITMQ_MACHINE_QUEUE_BINDING_KEY }}" >> .env
            echo "RABBITMQ_NOTIFICATION_QUEUE_BINDING_KEY=${{ vars.RABBITMQ_NOTIFICATION_QUEUE_BINDING_KEY }}" >> .env
            echo "RABBITMQ_EMPLOYEE_QUEUE_BINDING_KEY=${{ vars.RABBITMQ_EMPLOYEE_QUEUE_BINDING_KEY }}" >> .env
            echo "RABBITMQ_SUPPORT_CASE_QUEUE_BINDING_KEY=${{ vars.RABBITMQ_SUPPORT_CASE_QUEUE_BINDING_KEY }}" >> .env
            echo "RABBITMQ_MACHINE_QUEUE_NAME=${{ vars.RABBITMQ_MACHINE_QUEUE_NAME }}" >> .env
            echo "RABBITMQ_NOTIFICATION_QUEUE_NAME=${{ vars.RABBITMQ_NOTIFICATION_QUEUE_NAME }}" >> .env
            echo "RABBITMQ_EMPLOYEE_QUEUE_NAME=${{ vars.RABBITMQ_EMPLOYEE_QUEUE_NAME }}" >> .env
            echo "RABBITMQ_SUPPORT_CASE_QUEUE_NAME=${{ vars.RABBITMQ_SUPPORT_CASE_QUEUE_NAME }}" >> .env

            echo "📥 Pull latest image"
            docker-compose -f docker-compose.prod.yml pull

            echo "🚀 Restart containers"
            docker-compose -f docker-compose.prod.yml up -d

            echo "Cleanup old images..."
            docker image prune -f
          EOF